name: Fail Slack Notify Demo

on:
  workflow_dispatch:

jobs:
  fail-slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        id: fail
        shell: bash
        run: |
          exit 1

      - name: Set Slack Notify Parameter Dynamically
        if: always()
        id: set_slack_notify_parameter
        run: |
          if [ "${{ steps.success.outcome }}" == "success" ]; then
            echo "JOB_NAME='Slack Notify Success'" >> $GITHUB_ENV
          else
            echo ${{ steps.success.outcome }}
            echo "JOB_NAME='Slack Notify FAIL'" >> $GITHUB_ENV
          fi

      - name: Slack Notify
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          job_name: ${{ env.JOB_NAME }}
          status: ${{ steps.success.outcome }}
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
