name: Fail Slack Notify Demo

on:
  workflow_dispatch:

jobs:
  fail-slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Target Step
        id: target_step
        shell: bash
        run: |
          exit 1

      - name: Set Slack Notify Parameter Dynamically
        if: always()
        id: set_slack_notify_parameter
        run: |
          if [ "${{ steps.target_step.outcome }}" == "success" ]; then
            echo "JOB_NAME=Slack Notify Success" >> $GITHUB_ENV
          else
            echo "JOB_NAME=Slack Notify FAIL" >> $GITHUB_ENV
          fi

      - name: Slack Notify
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          text: ${{ env.JOB_NAME }}
          # icon_emoji: ':octocat:' Do not work
          status: ${{ steps.target_step.outcome }}
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
