name: Success Slack Notify Demo

on:
  workflow_dispatch:

jobs:
  success-slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        id: success
        shell: bash
        run: |
          echo "Success!"

      - name: Slack Notify
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          job_name: Slack Notify
          status: ${{ steps.success.outcome }}
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
